-- begin CHECKDCCONCEPT_A_MANY_TO_MANY_B
alter table CHECKDCCONCEPT_A_MANY_TO_MANY_B add constraint FK_CHECKDCCONCEPT_A_MANY_TO_MANY_B_ON_A foreign key (A_ID) references CHECKDCCONCEPT_A(ID)^
alter table CHECKDCCONCEPT_A_MANY_TO_MANY_B add constraint FK_CHECKDCCONCEPT_A_MANY_TO_MANY_B_ON_B foreign key (B_ID) references CHECKDCCONCEPT_B(ID)^
create index IDX_CHECKDCCONCEPT_A_MANY_TO_MANY_B_ON_A on CHECKDCCONCEPT_A_MANY_TO_MANY_B (A_ID)^
create index IDX_CHECKDCCONCEPT_A_MANY_TO_MANY_B_ON_B on CHECKDCCONCEPT_A_MANY_TO_MANY_B (B_ID)^
-- end CHECKDCCONCEPT_A_MANY_TO_MANY_B
